### PR TITLE
Add weekly Saturdays cron and update tagged versions

### PR DESCRIPTION
**Pull request by kaovilai**
as of this PR, latest would be golang 1.19.4
It would also add the following tags
- v1.19
- v1.19.4
- ubi9-v1.19
- ubi9-v1.19.4

### CODE REVIEW

**Comment by jmontleon** [comment]
Maybe weekly would be a more appropriate schedule?

These take about 4 hours to build across all archs for each ubi8 and 9. While there's no reason it can't be nightly I suppose, it seems like burning a lot of cycles for probably no gain most days.

**Comment by jmontleon** [comment]
Other than that comment no issue from me, looks good!

**Comment by kaovilai** [comment]
A way to speed these up would be to use one runner per arch then combine them at the end.
However the actions will look a bit messier.. basically what we do in travis for multi-arch

**Pull request merged**
